### ISSUE TITLE
Issues in presentation

### ISSUE THREAD

**Issue by TELEUZI** [MikAleinik/rs-webinar#2]
Так как у нас уже имеется ненумерованный список, то слово "Часть" писать не нужно, как и точки после "содержание", заголовков, в списках, и т.д.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L25

Оглавление не соответствует названиям слайдов. Не выполнялись реализация и рефакторинг кода. В оглавлении описывается содержание презентации. По данной причине, необходимо указать "создание объектов в JS", например.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L32

Нужно указать, что это только примеры создания объектов, можно оттуда даже убрать классы, и добавить `Object.create`, например, а уже на следующем слайде про классы.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L39

Необходимо объяснить назначение такого присвоения, раз оно в презентации.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#LL75C5-L75C5

Необходимо объяснить сначала, что такое классы, что такое объекты в контексте ООП, а потом уже в JS.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L62

Используй тире, а не дефис. "сначала необходимо определить класс и затем его использовать" это очевидное заявление, так как любую сущность нужно определить, а потом использовать. Нужно сказать, что обращение к классу до его объявления вызовет соответствующую ошибку.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L80

Используй параметры в конструкторе, передавай туда значения, функции и т.д. 
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L92

Необходим пробел перед комментарием
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L107

Подчёркивание не нужно, так как решётка указывает на приватность поля.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L113

Нужно указать, что при обращении через решётку будет ошибка (But not after chrome 111 in console https://developer.chrome.com/blog/new-in-devtools-111/#misc)
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L116

В JS нет защищённых полей. Это можно указазать как пример взаимодействия с приватным полем. Приватное подчёркивание не нужно.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#LL119C52-L119C52

Указать версию ECMA и версий браузеров, поддерживающих это. Необходимо поместить на предыдущий слайд. 
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L151

"модификатор public — поле доступно для всех". 
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L155

Сначала нужно определение, назначение, а потом пример. Нужно объяснить, что такое утилитарные классы.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L163

Все примеры кода должны быть подписаны. В этом, например, указать, что это пример проблемы, которую решает наследование.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L184

Почему `View`? Раз все `Page` от него наследуются, то логично назвать класс `BasePage`.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L204

Можно просто заменить на `return null` и использовать тернарку.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L235

Почему такое название? Это скорее принципы чистого кода для работы с классами.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L245

"Для облегчения восприятия кода класса необходимо:"
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L246

"Давать описательные, исчерпывающие, предметные, имена для классов"
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L248

Необходимо описать, что это за группы.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#LL250C37-L250C37

Зависит от принятого стайлгайда.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L254

Может конфликтовать с группировкой по приватности/публичности.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L258

Оглавление должно соответствовать содержанию презентации
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L290

https://ru.wikipedia.org/wiki/%D0%9E%D0%B4%D0%BD%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#LL299C53-L299C53

В JS нет никаких API-интерфейсов, это API браузера.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#LL300C85-L300C111

Подписать список, а не общая фраза про архитектуру.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L306

Очень редкие понятия, скорее локальные, не уверен, что они нужны, лучше более глубоко сравнить SPA vs MPA.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L310

Убрать текст, или переписать.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L319

Не структура, а архитектура, то же и для сервисов. Очепятка "микроСЕвисной"
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#LL324C86-L324C86

Маршрутизация между компонентами без перезагрузки страницы, скорее.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L334

Генерация разметки без участия сервера? Или убрать пункт, так как это может происходить и в MPA, а может и не происходить в SPA.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L335

Что за состояние?
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L336

Это скорее недостатки, а не особенности. И применимы, в основном, к CSR, а не SPA.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L340

Почему не два разных списка?
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L352

Контент не соответствует названию раздела. Если хочешь это объяснить, то заведи отдельный раздел, вставь картинки и тд.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L356

Что за состояние? Почему оно обязательно хранится? Почему состояние и в преимуществах и в недостатках? 
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L372

Это относится не только к SPA, оно тут не при чём.
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L374

Написать полностью, что за "модели"
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#LL377C67-L377C67

А большое количество кода в MPA на производительности не сказывается?
https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L391

Где аналогичное описание для MPA? С преимуществами и недостатками.

**Comment by MikAleinik** [comment]
Поправил.
> Так как у нас уже имеется ненумерованный список, то слово "Часть" писать не нужно, как и точки после "содержание", заголовков, в списках, и т.д.

Оглавление относилось к содержанию стрима, подправил.
> Не выполнялись реализация и рефакторинг кода. В оглавлении описывается содержание презентации. 

Дополнил список комментарием, изменил заголовок.
> Нужно указать, что это только примеры создания объектов, можно оттуда даже убрать классы, и добавить Object.create, например, а уже на следующем слайде про классы.

Добавил короткую секцию по ООП.
>Необходимо объяснить сначала, что такое классы, что такое объекты в контексте ООП, а потом уже в JS.

Исправил.
> Используй тире, а не дефис. 

Перефразировал, это сравнительно для объявления функций/классов
> "сначала необходимо определить класс и затем его использовать" это очевидное заявление, так как любую сущность нужно определить, а потом использовать.

Исправлено.
> Необходим пробел перед комментарием

Дурная привычка, исправлено.
> Подчёркивание не нужно, так как решётка указывает на приватность поля.

Дополнил.
> Нужно указать, что при обращении через решётку будет ошибка 

> В JS нет защищённых полей. Это можно указазать как пример взаимодействия с приватным полем. 

Дополнил.
> Указать версию ECMA и версий браузеров, поддерживающих это. Необходимо поместить на предыдущий слайд.

Перефразировал, дополнил.
> "модификатор public — поле доступно для всех".

Дополнил, но не вдавался в подробности.
> Сначала нужно определение, назначение, а потом пример. Нужно объяснить, что такое утилитарные классы.

Дополнил.
> Все примеры кода должны быть подписаны. В этом, например, указать, что это пример проблемы, которую решает наследование.

Исправлено.
> Почему View? Раз все Page от него наследуются, то логично назвать класс BasePage.

Дополнил.
> Можно просто заменить на return null и использовать тернарку.

Дополнил.
> Почему такое название? Это скорее принципы чистого кода для работы с классами.

Дополнил.
> "Давать описательные, исчерпывающие, предметные, имена для классов"

Дополнил вкратце.
> Необходимо описать, что это за группы.

Перефразировал и дополнил.
> Зависит от принятого стайлгайда.
> Может конфликтовать с группировкой по приватности/публичности.

Оглавление относилось к содержанию стрима, исправил
> Оглавление должно соответствовать содержанию презентации

Исправил, копипаст mdn)
> В JS нет никаких API-интерфейсов, это API браузера.

Дополнил кратким определением.
> Подписать список, а не общая фраза про архитектуру.

Исправил.
> Очень редкие понятия, скорее локальные, не уверен, что они нужны, лучше более глубоко сравнить SPA vs MPA.

Удалено.
> Убрать текст, или переписать.

Исправил.
> Не структура, а архитектура, то же и для сервисов. Очепятка "микроСЕвисной"

Не совсем однозначно - при вводе в строке браузера без использования # будет перезагрузка страницы,
Перефразировал.
> Маршрутизация между компонентами без перезагрузки страницы, скорее.

Исправил.
> Генерация разметки без участия сервера? Или убрать пункт, так как это может происходить и в MPA, а может и не происходить в SPA.

Забыл удалить секцию, исправлено.
> Почему не два разных списка?
> Контент не соответствует названию раздела. Если хочешь это объяснить, то заведи отдельный раздел, вставь картинки и тд.

Дополнил.
> Написать полностью, что за "модели"
> https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#LL377C67-L377C67

Дополнил.
> А большое количество кода в MPA на производительности не сказывается?

Не предполагаю его делать, т.к. акцент, изначально, планировался на SPA
> Где аналогичное описание для MPA? С преимуществами и недостатками.




Не понял мысль. Тут пример того, что может быть в классе.
> Используй параметры в конструкторе, передавай туда значения, функции и т.д.
> [rs-webinar/index.html](https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L92)
> 
> Line 92 in [ee549c1](https://github.com/MikAleinik/rs-webinar/commit/ee549c180def0b17afe99cee2b60757920329f6f)
> 
>  constructor() { 

Состояние данных в приложении после каких-либо действий пользователя. Понимаю, что это не только SPA особенность. Изменил заголовок, т.к. "Преимущества" должны быть в сравнении с чем-то.
> Что за состояние?
> [rs-webinar/index.html](https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L336)
> 
> Line 336 in [ee549c1](https://github.com/MikAleinik/rs-webinar/commit/ee549c180def0b17afe99cee2b60757920329f6f)
> 
>  <li class="fragment fade-up">Хранит собственное состояние при переходах.</li> 

Перефразировал заголовок. Но тут, если я верно понимаю, достаточно тонкая грань и я всегда ассоциировал SPA с приложениями которые сами себя рисуют и имеют маршрутизацию.
> Это скорее недостатки, а не особенности. И применимы, в основном, к CSR, а не SPA.
> [rs-webinar/index.html](https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L340)
>
> Line 340 in [ee549c1](https://github.com/MikAleinik/rs-webinar/commit/ee549c180def0b17afe99cee2b60757920329f6f)
> 
> <h5>Особенности SPA приложения.</h5> 

Одна из плюшек SPA в том, что серверная часть не содержит ни чего, что относится к разметке, а значит и разделение разработки клиент/сервер более явное. Не так?
> Это относится не только к SPA, оно тут не при чём.
> [rs-webinar/index.html](https://github.com/MikAleinik/rs-webinar/blob/ee549c180def0b17afe99cee2b60757920329f6f/index.html#L374)
> 
> Line 374 in [ee549c1](https://github.com/MikAleinik/rs-webinar/commit/ee549c180def0b17afe99cee2b60757920329f6f)
> 
>  <li class="fragment fade-up">Разделение клиент/сервер - на сервере не остается логики
