### ISSUE TITLE
SPA HashRouterHandle does not work

### ISSUE THREAD

**Issue by bearury** [MikAleinik/rs-webinar#3]
Hello! I've been looking into your code. I have reached the implementation of **HashRouter/HistoryRouter** As far as I understand, this method is not called https://github.com/MikAleinik/rs-webinar/blob/93208208ed8a0188245c3f836f713ce1df88d183/example/src/spa/router/router.js#L22. Accordingly, the hash router does not work. I checked twice.

**Comment by MikAleinik** [comment]
Привет @webjsmaster !
В коде действительно была ошибка - большое спасибо за помощь.
Я внес исправления. Буду очень признателен если вы проверите и подтвердите, что у вас все работает как ожидается - тогда я спокойно закрою замечание.

**Comment by bearury** [comment]
Да, сейчас все работает! Спасибо!
